### ISSUE TITLE
Fox Build Issues while setting up Paraview for H100 GPUs.

### ISSUE THREAD

**Issue by sherinsugathan** [NAICNO/HPC-Visualization#1]
Local Installation of Qt5-5.15.7-GCCcore-12.2.0.eb was attempted on Fox but failed.
The package is needed for building latest Paraview 5.11.1 with foss/2022b toolchain.
The Qt5 recipe was failing because nodejs was raising spawning related issues as per the log.
Relevant portion of the failure log is attached.
[Qt5ErrorLog.txt](https://github.com/NAICNO/HPC-Visualization/files/13260583/Qt5ErrorLog.txt)

Solving this issue may require setting system ulimits, but not sure.
A potential solution to this issue can include an administrator attempting a system-wide install of Qt5-5.15.7-GCCcore-12.2.0.eb

**Comment by Sabryr** [comment]
I will check this

**Comment by Sabryr** [comment]
@sherinsugathan I think the reason was that there were step in compilation taking very long time and there were some stale file handlers or something similar.    I managed to build this by using `--parallel 128` to make compilation faster

`
eb --parallel 128 --configfile=/cluster/software/EL9/easybuild/config.cfg --robot Qt5-5.15.7-GCCcore-12.2.0.eb
`
To use this module (still hidden)

`
module --ignore-cache avail qt5/5.15.7-GCCcore-12.2.0
`

Regards,
Sabry

**Comment by sherinsugathan** [comment]
issue resolved and closing.
